apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: monitoring
  labels:
    app: sample-app   #i   
spec:
  selector:
    app: sample-app   #i
  ports:
  - name: http        #i
    port: 9100
    targetPort: 9100